name: wavetorch4
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - certifi=2023.11.17
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - contourpy=1.2.0
  - cryptography=41.0.3
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - expat=2.5.0
  - ffmpeg=4.3
  - filelock=3.13.1
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=73.1
  - idna=3.4
  - intel-openmp=2023.1.0
  - jinja2=3.1.2
  - jpeg=9e
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.8.1.2
  - libcups=2.4.2
  - libcurand=10.3.4.101
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libllvm14=14.0.6
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libpq=12.15
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.10.4
  - llvm-openmp=14.0.6
  - llvmlite=0.41.0
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - munkres=1.1.4
  - mysql=5.7.24
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.1
  - numba=0.58.0
  - numexpr=2.8.7
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.0.12
  - packaging=23.1
  - pandas=2.1.1
  - pcre=8.45
  - pillow=10.0.1
  - pip=23.3.1
  - ply=3.11
  - pycparser=2.21
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.11.5
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - pytorch=2.1.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - qt-main=5.15.2
  - readline=8.2
  - requests=2.31.0
  - setuptools=68.0.0
  - sip=6.7.12
  - six=1.16.0
  - sqlite=3.41.2
  - sympy=1.11.1
  - tbb=2021.8.0
  - tk=8.6.12
  - torchaudio=2.1.1
  - torchtriton=2.1.0
  - torchvision=0.16.1
  - tornado=6.3.3
  - typing_extensions=4.7.1
  - tzdata=2023c
  - urllib3=1.26.18
  - wheel=0.41.2
  - xz=5.4.2
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - asttokens==2.4.1
      - audioread==3.0.1
      - comm==0.2.0
      - data==0.4
      - debugpy==1.8.0
      - decorator==5.1.1
      - executing==2.0.1
      - funcsigs==1.0.2
      - future==0.18.3
      - imageio==2.33.0
      - ipykernel==6.27.1
      - ipython==8.18.1
      - jedi==0.19.1
      - joblib==1.3.2
      - jupyter-client==8.6.0
      - jupyter-core==5.5.0
      - latex==0.7.0
      - lazy-loader==0.3
      - librosa==0.10.1
      - matplotlib-inline==0.1.6
      - msgpack==1.0.7
      - nest-asyncio==1.5.8
      - parso==0.8.3
      - pexpect==4.9.0
      - platformdirs==4.0.0
      - pooch==1.8.0
      - prompt-toolkit==3.0.41
      - psutil==5.9.6
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pygments==2.17.2
      - pyzmq==25.1.2
      - scikit-image==0.22.0
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - seaborn==0.13.1
      - shutilwhich==1.1.0
      - soundfile==0.12.1
      - soxr==0.3.7
      - stack-data==0.6.3
      - tempdir==0.7.1
      - threadpoolctl==3.2.0
      - tifffile==2023.9.26
      - traitlets==5.14.0
      - wcwidth==0.2.12
